/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "EndStops_1.h"
#include "EndStops_1_aliases.h"
#include "EndStopSampleFreq.h"
#include "ADC_SAR_Seq_1.h"
#include "EndStopCtrl.h"
#include "Thermistors_aliases.h"
#include "TrianmicEnable.h"
#include "TrianmicEnable_aliases.h"
#include "DriverSPI.h"
#include "DriverSPI_SPI_UART.h"
#include "DriverSPI_PINS.h"
#include "DriverSPI_SPI_UART_PVT.h"
#include "DriverSPI_PVT.h"
#include "DriverSPI_BOOT.h"
#include "EndStopISR.h"
#include "EndStopStatus.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "ADC_SAR_Seq_1_intClock.h"
#include "DriverSPI_SCBCLK.h"
#include "DriverSPI_ss3_m.h"
#include "DriverSPI_ss3_m_aliases.h"
#include "DriverSPI_ss2_m.h"
#include "DriverSPI_ss2_m_aliases.h"
#include "DriverSPI_ss1_m.h"
#include "DriverSPI_ss1_m_aliases.h"
#include "DriverSPI_sclk_m.h"
#include "DriverSPI_sclk_m_aliases.h"
#include "DriverSPI_miso_m.h"
#include "DriverSPI_miso_m_aliases.h"
#include "DriverSPI_mosi_m.h"
#include "DriverSPI_mosi_m_aliases.h"
#include "DriverSPI_ss0_m.h"
#include "DriverSPI_ss0_m_aliases.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

